// This file was autogenerated by print_selective_registration_header.py
#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER

    namespace {
      constexpr const char* skip(const char* x) {
        return (*x) ? (*x == ' ' ? skip(x + 1) : x) : x;
      }

      constexpr bool isequal(const char* x, const char* y) {
        return (*skip(x) && *skip(y))
                   ? (*skip(x) == *skip(y) && isequal(skip(x) + 1, skip(y) + 1))
                   : (!*skip(x) && !*skip(y));
      }

      template<int N>
      struct find_in {
        static constexpr bool f(const char* x, const char* const y[N]) {
          return isequal(x, y[0]) || find_in<N - 1>::f(x, y + 1);
        }
      };

      template<>
      struct find_in<0> {
        static constexpr bool f(const char* x, const char* const y[]) {
          return false;
        }
      };
    }  // end namespace
    constexpr const char* kNecessaryOpKernelClasses[] = {
"BinaryOp< CPUDevice, functor::add<float>>",
"ApplyGradientDescentOp<CPUDevice, float>",
"ArgMaxOp<CPUDevice, float, int64>",
"AssignOpT<CPUDevice, float>",
"BCastGradArgsOp<int32>",
"CpuCastOp",
"ConstantOp",
"BinaryOp< CPUDevice, functor::equal_to<float>>",
"BinaryOp< CPUDevice, functor::equal_to<int64>>",
"ExpandDimsOp<int32>",
"FillOp<CPUDevice, float, int32>",
"BinaryOp< CPUDevice, functor::greater<float>>",
"IdentityOp",
"MatMulOp<CPUDevice, float, false >",
"ReductionOp<CPUDevice, float, int32, Eigen::internal::MeanReducer<float>>",
"BinaryOp< CPUDevice, functor::mul<float>>",
"UnaryOp< CPUDevice, functor::neg<float>>",
"NoOp",
"PlaceholderOp",
"IdentityOp",
"BinaryOp< CPUDevice, functor::div<float>>",
"ReshapeOp",
"SelectOp<CPUDevice, float>",
"ShapeOp<int32>",
"SparseSoftmaxXentWithLogitsOp<CPUDevice, float, int64>",
"ReductionOp<CPUDevice, float, int32, Eigen::internal::SumReducer<float>>",
"TileOp<CPUDevice, int32>",
"VariableOp",
"ZerosLikeOp< CPUDevice, float>",
"RecvOp",
"SendOp",
};
#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

constexpr inline bool ShouldRegisterOp(const char op[]) {
  return false
     || isequal(op, "Add")
     || isequal(op, "ApplyGradientDescent")
     || isequal(op, "ArgMax")
     || isequal(op, "Assign")
     || isequal(op, "BroadcastGradientArgs")
     || isequal(op, "Cast")
     || isequal(op, "Const")
     || isequal(op, "Equal")
     || isequal(op, "ExpandDims")
     || isequal(op, "Fill")
     || isequal(op, "Greater")
     || isequal(op, "Identity")
     || isequal(op, "MatMul")
     || isequal(op, "Mean")
     || isequal(op, "Mul")
     || isequal(op, "Neg")
     || isequal(op, "NoOp")
     || isequal(op, "Placeholder")
     || isequal(op, "PreventGradient")
     || isequal(op, "RealDiv")
     || isequal(op, "Reshape")
     || isequal(op, "Select")
     || isequal(op, "Shape")
     || isequal(op, "SparseSoftmaxCrossEntropyWithLogits")
     || isequal(op, "Sum")
     || isequal(op, "Tile")
     || isequal(op, "VariableV2")
     || isequal(op, "ZerosLike")
     || isequal(op, "_Recv")
     || isequal(op, "_Send")
  ;
}
#define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)

#define SHOULD_REGISTER_OP_GRADIENT false
#endif
